preset: symfony

enabled:
  - align_phpdoc
  - alpha_ordered_imports
  - array_indentation
  - compact_nullable_typehint
  - const_visibility_required
  - no_alternative_syntax
  - no_blank_lines_between_traits
  - no_unreachable_default_argument_value
  - short_array_syntax

disabled:
  - phpdoc_no_empty_return
  - phpdoc_to_comment
  - phpdoc_var_without_name
